# Generated by Django 2.0.2 on 2018-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chemicals',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('casn', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('name_synonyms', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('formula', models.IntegerField()),
                ('mw', models.IntegerField()),
                ('IUPAC', models.CharField(max_length=30)),
                ('SMILES', models.CharField(max_length=30)),
                ('PubChemFP', models.CharField(max_length=30)),
            ],
        ),
    ]
