# Generated by Django 2.0.2 on 2018-03-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_toxicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicity',
            name='spid',
            field=models.CharField(max_length=30),
        ),
    ]
