# Generated by Django 2.0.2 on 2018-03-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180301_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='targets',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('aeid', models.IntegerField()),
                ('intended_target_type', models.CharField(max_length=30)),
                ('intended_target_type_sub', models.CharField(max_length=30)),
                ('intended_target_family', models.CharField(max_length=30)),
                ('intended_target_family_sub', models.CharField(max_length=30)),
                ('intended_target_gene_id', models.CharField(max_length=30)),
                ('intended_target_entrez_gene_id', models.CharField(max_length=30)),
                ('intended_target_official_full_name', models.CharField(max_length=30)),
                ('intended_target_gene_name', models.CharField(max_length=30)),
                ('intended_target_official_symbol', models.CharField(max_length=30)),
                ('intended_target_gene_symbol', models.CharField(max_length=30)),
                ('intended_target_description', models.CharField(max_length=30)),
                ('intended_target_uniprot_accession_number', models.CharField(max_length=30)),
                ('intended_target_organism_id', models.CharField(max_length=30)),
                ('intended_target_track_status', models.CharField(max_length=30)),
                ('technological_target_gene_id', models.CharField(max_length=30)),
                ('technological_target_entrez_gene_id', models.CharField(max_length=30)),
                ('technological_target_official_full_name', models.CharField(max_length=30)),
                ('technological_target_gene_name', models.CharField(max_length=30)),
                ('technological_target_official_symbol', models.CharField(max_length=30)),
                ('technological_target_gene_symbol', models.CharField(max_length=30)),
                ('technological_target_description', models.CharField(max_length=30)),
                ('technological_target_uniprot_accession_number', models.CharField(max_length=30)),
                ('technological_target_organism_id', models.CharField(max_length=30)),
                ('technological_target_track_status', models.CharField(max_length=30)),
            ],
        ),
    ]
