# Generated by Django 2.0.2 on 2018-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targets',
            name='intended_target_entrez_gene_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targets',
            name='intended_target_gene_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targets',
            name='intended_target_organism_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targets',
            name='technological_target_entrez_gene_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targets',
            name='technological_target_gene_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='targets',
            name='technological_target_organism_id',
            field=models.IntegerField(),
        ),
    ]
