# Generated by Django 2.0.2 on 2018-03-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180304_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chemicals',
        ),
        migrations.DeleteModel(
            name='toxicity',
        ),
    ]
