# Generated by Django 2.0.2 on 2018-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180306_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targets',
            name='intended_target_gene_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targets',
            name='intended_target_official_full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targets',
            name='technological_target_gene_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targets',
            name='technological_target_official_full_name',
            field=models.CharField(max_length=50),
        ),
    ]
