# Generated by Django 2.0.2 on 2018-03-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180307_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='citation_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aeid', models.CharField(max_length=50)),
                ('citation_id', models.CharField(max_length=50)),
                ('pmid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='target_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aeid', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='citations',
            new_name='citation',
        ),
        migrations.RenameModel(
            old_name='experiments',
            new_name='experiment',
        ),
        migrations.RenameModel(
            old_name='targets',
            new_name='target',
        ),
    ]
