# Generated by Django 2.0.2 on 2018-03-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180307_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation_id',
            name='aeid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citation_id',
            name='citation_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citation_id',
            name='pmid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target_id',
            name='aeid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='target_id',
            name='target_id',
            field=models.IntegerField(),
        ),
    ]
