# Generated by Django 2.0.2 on 2018-03-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180307_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='experiment_target_relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experiment')),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.target')),
            ],
        ),
        migrations.RenameModel(
            old_name='citation_id',
            new_name='experiment_citation_relation',
        ),
        migrations.DeleteModel(
            name='target_id',
        ),
    ]
