# Generated by Django 2.0.2 on 2018-03-07 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180307_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_citation_relation',
            name='aeid',
            field=models.ForeignKey(db_column='aeid', on_delete=django.db.models.deletion.CASCADE, to='home.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment_citation_relation',
            name='citation_id',
            field=models.ForeignKey(db_column='citation_id', on_delete=django.db.models.deletion.CASCADE, to='home.citation'),
        ),
        migrations.AlterField(
            model_name='experiment_target_relation',
            name='aeid',
            field=models.ForeignKey(db_column='aeid', on_delete=django.db.models.deletion.CASCADE, to='home.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment_target_relation',
            name='target_id',
            field=models.ForeignKey(db_column='target_id', on_delete=django.db.models.deletion.CASCADE, to='home.target'),
        ),
    ]
