# Generated by Django 2.0.2 on 2018-03-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180307_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='pmid',
            field=models.IntegerField(null=True),
        ),
    ]
