# Generated by Django 2.0.2 on 2018-03-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chemicals',
        ),
    ]
